### CONFIGURATION ###



## GENERAL ##
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 298
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

##Enable cloud
cloud:
  google_actions:
    filter:
      include_entities:
       - group.firstfloorlights
       - group.secondfloorlights
       - group.bedroomlamps
       - group.decorative
       - group.fireplace_lights
       - group.color
       - group.christmas_lights
       - fan.bedroom
      include_domains:
       - light
      exclude_domains:
       - group
       - switch
       - input_boolean
       - script
       - automation
       - scene
       - climate
       - media_player
       - cover
      exclude_entities:
       - light.left_lamp
       - light.right_lamp
       - light.floor_lamp
       - light.liam_lamp
       - light.ryans_bloom
       - light.kristis_bloom
       - light.ryan_reading_lamp
       - light.kristi_reading_lam
       - light.play_room_lamp
       - light.office_lamp
       - light.spare_lamp
#  entity_config:
#        group.color:
#          name: Color Lights
#            aliases:
#             - stupid lights



# Show links to resources in log and frontend
# introduction:

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  trusted_networks:
    - 192.168.1.0/24
    - 127.0.0.1



# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Add Config Panel
config:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# Enable map
map:

# View all events in a logbook
logbook:

##Enable Recorder for Persistant input_select
recorder:
  purge_interval: 2
  purge_keep_days: 5

# Track the sun
sun:

ios:

#Add WeMo
wemo:

#Config for Zwave (added via interface)
zwave:
  polling_interval: 30000
  
#Python Scripting
python_script:

#Add Input Select
input_select:
  home_status:
    name: Status of House
    options:
    - Home
    - Away
    - Vacation
    - Sleep
    icon: mdi:House

  washing_machine_status:
    name: Washing Machine
    options:
    - Idle
    - Running
    - Clean
    icon: mdi:washing-machine

  dryer_status:
    name: Dryer
    options:
    - Idle
    - Running
    - Clean
    icon: mdi:washing-machine

  ryan_phone_status:
    name: Ryans Phone Status
    options:
    - On Battery
    - Charging
    - Low Battery
    - In Car
    - Sleep
    initial: On Battery
    icon: mdi:cellphone-android

  kristi_phone_status:
    name: Kristis Phone Status
    options:
    - On Battery
    - Charging
    - Low Battery
    - In Car
    - Sleep
    initial: On Battery
    icon: mdi:cellphone-android

  gmusic_playlists:
    name: Google Music Playlist
    options:
    - Thumbs Up
    - Yoga
    - Deep Beats
    - Worship
    - Morning Flow
    - Meditate Nature
    - TransAtlantic Lullaby
    - SPA Treatment

  media_speakers:
    name: Media Speakers
    options:
    - Home Group
    - Bedroom Suite
    - Bedroom Home
    - Bathroom Home
    - Office Home
    - Office Speakers
    - Kitchen Home
    - Soundbar

  zigbee2mqtt_log_level:
    name: Zigbee2mqtt Log Level
    options:
     - debug
     - info
     - warn
     - error
    initial: info
    icon: mdi:format-list-bulleted

ifttt:
  key: !secret ifttt_key

weather:
  - platform: darksky
    api_key: !secret dark_sky_api
    mode: daily

#APCUPS
#apcupsd:

#JOIN
# joaoapps_join:
#   - name: Join
#     device_id: group.join
#     api_key: !secret join_key

mqtt:
  broker: !secret mqtt_ip
  port: 1883
  client_id: haas
  keepalive: 60
  protocol: 3.1.1
  discovery: true 
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'


media_player:
  - platform: plex
  - platform: cast
  - platform: roku
  - platform: webostv
    host: !secret play_tv_ip
  # - platform: xboxone
  #   device: !secret xbox_one
  #   name: Xbox One

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

google:
  client_id: !secret google_id
  client_secret: !secret google_secret

ring:
  username: !secret email
  password: !secret ring_pass

# alarm_control_panel:
#   platform: mqtt
#   state_topic: "smartthings/alarm system status/alarmSystemStatus/state"
#   command_topic: "smartthings/alarm system status/alarmSystemStatus/set"
#   name: "SHM"
#   payload_disarm: "disarmed"
#   payload_arm_home: "armed_home"
#   payload_arm_away: "armed_away"
#   code: !secret alarmcode

alarm_control_panel:
  - platform: manual_mqtt
    name: "SHM"
    state_topic: "smartthings/alarm system status/alarmSystemStatus/state"
    command_topic: "smartthings/alarm system status/alarmSystemStatus/set"
    payload_disarm: "disarmed"
    payload_arm_home: "armed_home"
    payload_arm_away: "armed_away"
    pending_time: 45
    code: !secret alarmcode
    delay_time: 30
    trigger_time: 4
    disarmed:
      trigger_time: 0
    triggered:
      pending_time: 0

tts:
  - platform: google
    language: 'en-us'
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

#google_assistant:
#  project_id: !secret ga_project
#  client_id: !secret ga_id
#  access_token: !secret ga_token

shell_command:
  get_latest_config: bash /home/homeassistant/.homeassistant/bin/update_config_from_github.sh
  restart_mqtt: docker restart mqtt_bridge

climate:
  platform: nest

device_tracker:
  # - platform: unifi
  #   username: !secret email
  #   password: !secret unifi_pass
  #   host: !secret server_ip
  #   port: 8443
  #   verify_ssl: false
  #   new_device_defaults:
  #     track_new_devices: true
  #     hide_if_away: False
  - platform: ping
    hosts:
      mom: !secret mom_ip
  - platform: google_maps
    username: !secret google_user
    password: !secret google_pass
    max_gps_accuracy: 500

#Cameras
camera:
  - platform: mjpeg
    mjpeg_url: !secret baby_cam_url
    name: Baby Camera
  - platform: mjpeg
    mjpeg_url: !secret deck_cam_url
    name: Back Deck Camera
  - platform: mjpeg
    mjpeg_url: !secret play_cam_url
    name: Play Room Camera
  - platform: mjpeg
    mjpeg_url: !secret front_cam_url
    name: Front House Camera
  - platform: mjpeg
    mjpeg_url: !secret basement_cam_url
    name: Basement
  - platform: mjpeg
    name: Living Room
    mjpeg_url: !secret lr_cam_url
  - platform: mjpeg 
    name: Garage Camera
    mjpeg_url: !secret garage_cam_url
  - platform: ring
  - platform: usps
    scan_interval: 5

ffmpeg:

#zoneminder:
#  host: !secret ZM_HOST
#  path: /zm
#  path_zms: /zm/cgi-bin/nph-zms
#  ssl: False
#  username: !secret ZM_USERNAME
#  password: !secret ZM_PASSWORD

##USPS Package Tracking
usps:
    username: !secret usps_user
    password: !secret usps_pass
    driver: chrome

cover:
  - platform: myq
    username: !secret email
    password: !secret myq_pass
    type: liftmaster

rachio:
  api_key: !secret rachio_api

proximity:
  home:
    ignored_zones:
      - Pivot
      - Mason
    devices:
      - device_tracker.google_maps_118314383764095593834
      - device_tracker.google_maps_114680120030307638360
    tolerance: 50
    unit_of_measurement: mi

hue:
  bridges:
    - host: !secret hue_ip
      allow_unreachable: true
      allow_hue_groups: false

# insteon:
#   host: !secret insteon_ip
#   ip_port: !secret insteon_port
#   username: !secret insteon_user
#   password: !secret insteon_pass
#   hub_version: 2    

# panel_custom:
#   - name: floorplan
#     sidebar_title: Floorplan
#     sidebar_icon: mdi:home
#     url_path: floorplan
#     config: !include floorplan.yaml
    
telegram_bot: 
  - platform: polling 
    api_key: !secret telegram_api 
    allowed_chat_ids: 
      - !secret telegram_ryan

panel_iframe:
  rachio:
    title: Rachio
    url: "https://app.rach.io"
    icon: mdi:water-pump
  terminal:
    title: Terminal
    icon: mdi:console
    url: "https://hollandhaus.duckdns.org:7681"
  pihole:
    title: Pi-hole
    icon: mdi:block-helper
    url: "http://hollandhaus.duckdns.org:4865"
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120

sabnzbd:
  api_key: !secret sabnzbd_api
  host: !secret server_ip
  name: sab
  port: 8085
  ssl: false
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

##Add System Health
system_health:

#Speedtest
speedtestdotnet:

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################

##Zones
zone: !include zones.yaml

##Notify
notify: !include notify.yaml

##Groups
group: !include groups.yaml

##Scenes
scene: !include scenes.yaml

##Sensors
sensor: !include sensors.yaml

##Automation
automation: !include automation/automation.yaml

##Switches
switch: !include switches.yaml

##Scripts
script: !include scripts.yaml

##Binary Sensor
binary_sensor: !include binary.yaml

##Alerts
alert: !include alert.yaml

##Locks
lock: !include lock.yaml

##Lights
light: !include lights.yaml

##input_boolean
input_boolean: !include input_boolean.yaml

##Frontend
frontend: !include frontend.yaml

##rest_commands
rest_command: !include rest.yaml
