### CONFIGURATION ###



## GENERAL ##
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 298
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

##Enable cloud
cloud:

influxdb:
  host: 192.168.1.250

# Show links to resources in log and frontend
# introduction:

http:
  # api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
#  trusted_networks:
#    - 192.168.1.0/24



# Checks for available updates
updater:

# Discover some devices automatically
discovery:


# Add Config Panel
config:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# Enable map
map:

# View all events in a logbook
logbook:

##Enable Recorder for Persistant input_select
recorder:
  purge_interval: 2
  purge_keep_days: 5

# Track the sun
sun:

ios:

mobile_app: 

#Add WeMo
wemo:
  static:
    - 192.168.1.65
    - 192.168.1.66
    - 192.168.1.67

#Config for Zwave (added via interface)
zwave:
  polling_interval: 30000
  config_path: /config/zwave/config
  
#Python Scripting
python_script:

#Add Input Select
input_select:
  home_status:
    name: Status of House
    options:
    - Home
    - Away
    - Vacation
    - Sleep
    icon: mdi:House

  washing_machine_status:
    name: Washing Machine
    options:
    - Idle
    - Running
    - Clean
    icon: mdi:washing-machine

  dryer_status:
    name: Dryer
    options:
    - Idle
    - Running
    - Clean
    icon: mdi:tumble-dryer

  dishwasher_status:
    name: Dishwasher
    options:
    - Idle
    - Running
    - Clean
    icon: mdi:dishwasher

  chromebook_status:
    name: Chromebook
    options:
    - Unplugged
    - Charging
    - PluggedIn
    icon: mdi:laptop-chromebook

  ryan_phone_status:
    name: Ryans Phone Status
    options:
    - On Battery
    - Charging
    - Low Battery
    - In Car
    - Sleep
    initial: On Battery
    icon: mdi:cellphone-android

  kristi_phone_status:
    name: Kristis Phone Status
    options:
    - On Battery
    - Charging
    - Low Battery
    - In Car
    - Sleep
    initial: On Battery
    icon: mdi:cellphone-android

  gmusic_playlists:
    name: Google Music Playlist
    options:
    - Thumbs Up
    - Yoga
    - Deep Beats
    - Worship
    - Morning Flow
    - Meditate Nature
    - TransAtlantic Lullaby
    - SPA Treatment

  media_speakers:
    name: Media Speakers
    options:
    - Home Group
    - Bedroom Suite
    - Bedroom Home
    - Bathroom Home
    - Office Home
    - Office Speakers
    - Kitchen Home
    - Soundbar

  zigbee2mqtt_log_level:
    name: Zigbee2mqtt Log Level
    options:
     - debug
     - info
     - warn
     - error
    initial: info
    icon: mdi:format-list-bulleted

input_datetime:
  liam_wake:
    name: Liam's Wake Up Time
    has_date: false
    has_time: true
  liam_night_light:
    name: Liam's Night Light
    has_date: false
    has_time: true

ifttt:
  key: !secret ifttt_key

weather:
  - platform: darksky
    api_key: !secret dark_sky_api
    mode: daily

#APCUPS
apcupsd:
  host: a722577e-apcupsd

media_player:
# - platform: roku
#  host: !secret roku_one
# - platform: webostv
#  host: !secret play_tv_ip
  # - platform: xboxone
  #   device: !secret xbox_one
  #   name: Xbox One
  
# roku:
#   - host: !secret roku_one
#   - host: !secret roku_two
#   - host: !secret roku_three

webostv:
  host: !secret play_tv_ip
  name: Play Room TV

# nest:
#  client_id: !secret nest_id
#  client_secret: !secret nest_secret

badnest:
  issue_token: !secret new_nest_token
  cookie: !secret new_nest_cookie
  region: us

##Google for Google Calendar
# google:
#   client_id: !secret google_id
#   client_secret: !secret google_secret

# ring:
#   username: !secret email
#   password: !secret ring_pass

# alarm_control_panel:
#   platform: mqtt
#   state_topic: "smartthings/alarm system status/alarmSystemStatus/state"
#   command_topic: "smartthings/alarm system status/alarmSystemStatus/set"
#   name: "SHM"
#   payload_disarm: "disarmed"
#   payload_arm_home: "armed_home"
#   payload_arm_away: "armed_away"
#   code: !secret alarmcode

alarm_control_panel:
  - platform: manual_mqtt
    name: "SHM"
    state_topic: "smartthings/alarm system status/alarmSystemStatus/state"
    command_topic: "smartthings/alarm system status/alarmSystemStatus/set"
    payload_disarm: "disarmed"
    payload_arm_home: "armed_home"
    payload_arm_night: "armed_home"
    payload_arm_away: "armed_away"
    pending_time: 45
    code: !secret alarmcode
    delay_time: 30
    trigger_time: 30
    disarmed:
      trigger_time: 0
    triggered:
      pending_time: 0
    # arm_night:
    #   pending_time: 0
    #   trigger_time: 15

tts:
  - platform: google_translate
    language: 'en-us'
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: http://192.168.1.5:8123
#google_assistant:
#  project_id: !secret ga_project
#  client_id: !secret ga_id
#  access_token: !secret ga_token

shell_command:
  get_latest_config: bash /home/homeassistant/.homeassistant/bin/update_config_from_github.sh

climate:
  - platform: nest
  - platform: badnest
    scan_interval: 10

device_tracker:
  - platform: google_maps
    username: !secret google_user
    # password: !secret google_pass
    max_gps_accuracy: 500
  - platform: tile
    username: !secret email
    password: !secret tile_pass

ffmpeg:

cover:
  - platform: myq
    username: !secret email
    password: !secret myq_pass
    type: liftmaster

rachio:
  api_key: !secret rachio_api

proximity:
  home:
    ignored_zones:
      - Pivot
      - Mason
    devices:
      - device_tracker.google_maps_118314383764095593834
      - device_tracker.google_maps_114680120030307638360
    tolerance: 50
    unit_of_measurement: mi
   
telegram_bot: 
  - platform: webhooks 
    api_key: !secret telegram_api 
    allowed_chat_ids: 
      - !secret telegram_ryan

# panel_iframe:
#   grafana:
#     title: Grafana
#     icon: mdi:graph
#     url: "https://hollandhaus.duckdns.org:3000"

panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph2
    sidebar_icon: mdi:access-point-network
    url_path: zwave
    
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120
  wax_melter:
    name: Wax Melt Time
    duration: 1800

##Add System Health
system_health:

#Speedtest
speedtestdotnet:

##Add Google Home Tracker / Alarms
# googlehome:
#   devices:
#     - host: 192.168.1.245
#       track_alarms: true
#     - host: 192.168.1.253
#       track_alarms: true
#     - host: 192.168.1.242
#       track_alarms: true
#     - host: 192.168.1.246
#       track_alarms: true

##Add Person
person:

#Add Xiaomi Gateway
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_token
      host: !secret xiaomi_ip
      
circadian_lighting:
  sunrise_offset: +01:00:00
  sunset_offset: -01:00:00

wyzeapi:
  username: !secret email
  password: !secret wyze_pass

vacuum:
  platform: xiaomi_miio
  host: !secret max_ip
  token: !secret roborock

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################

##Zones
zone: !include zones.yaml

##Notify
notify: !include notify.yaml

##Groups
group: !include groups.yaml

##Scenes
scene: !include scenes.yaml

##Sensors
sensor: !include sensors.yaml

##Automation
automation: !include automations.yaml

##Switches
switch: !include switches.yaml

##Scripts
script: !include scripts.yaml

##Binary Sensor
binary_sensor: !include binary.yaml

##Alerts
alert: !include alert.yaml

##Locks
lock: !include lock.yaml

##Lights
light: !include lights.yaml

##input_boolean
input_boolean: !include input_boolean.yaml

##Frontend
frontend:
  themes: !include_dir_merge_named themes

##rest_commands
rest_command: !include rest.yaml

##cameras
camera: !include cameras.yaml
